Add `--same-password` flag for reading only one password for both files
Narigo/keepass-diff pull request #30
Opened 2021-02-01 22:34 UTC by Tezkerek

2021-02-02 18:45 UTC, Narigo requested changes
Hi @Tezkerek thanks for this PR!

I had some trouble initially why you want to add a `--same-password` flag as there is `--passwords` already to set both. After finally understanding that one prompt instead of two makes totally sense, this is a really good idea and thanks for taking the time implementing this feature!

If you have time to help out more, you could add the new thing to the Readme, fix the formatting issue, add a test and update the package version to 1.1.0. I can then test it, merge and publish a new version directly.

2021-02-02 19:20 UTC, Tezkerek commented on src/main.rs
> +      .takes_value(false),
Yeah, I forgot to undo that while debugging why my indent detection plugin was setting the indent to 2 spaces.  The rest of the file is indented with 4 spaces, but lines 23-108 are indented with only 2? And rustfmt doesn't seem to care about the indentation in parameters?

2021-02-02 19:23 UTC, Tezkerek commented
I don't see any tests for `keepass-diff <file-a> <file-b>`, should the test just check that opening the databases doesn't fail?

2021-02-08 01:58 UTC, Narigo approved these changes
Thanks for adding the documentation and updating the version!

2021-02-08 02:00 UTC, Narigo commented
> I don't see any tests for `keepass-diff <file-a> <file-b>`; should the test just check that opening the databases doesn't fail?

Ahh, you're right. I guess I haven't added anything yet for the ones relying on user inputs. I've tested it manually now, it works - so I'll merge it. It looks like it's possible to pipe input into this but then the output does not start on a new line and I'd need to somehow change that. I'll merge this PR now and add an issue for this. Thanks again for the contribution!

2021-02-08 02:00 UTC, merged